---

- name: "Install sudo (via apt)"
  include: apt-install-sudo.yml

- name: "Create ansible deploy user"
  include: deploy-user.yml

- name: "Disallow root SSH access"
  include: disallow-root-ssh.yml
